version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: logvin
      POSTGRES_PASSWORD: logvin
      POSTGRES_DB: todo
#  adminer:
#    image: adminer:4.7.8-standalone
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "./wait-for-postgres.sh db && python manage.py migrate && python manage.py users_create && gunicorn todo.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    depends_on:
      - backend
